if(NOT DEFINED RUNNER_SOURCE_DIR)
    message(FATAL_ERROR "RUNNER_SOURCE_DIR was not provided")
endif()

foreach(required IN ITEMS CHANGELOG.md missioncache.md README.md docs/SANDHYBRID_INTEGRATION_BRIDGE.md)
    if(NOT EXISTS "${RUNNER_SOURCE_DIR}/${required}")
        message(FATAL_ERROR "Missing required repository document: ${required}")
    endif()
endforeach()

file(GLOB release_notes "${RUNNER_SOURCE_DIR}/RELEASE_NOTES*.md")
if(release_notes)
    list(JOIN release_notes ", " release_note_list)
    message(FATAL_ERROR "Per-release note files remain: ${release_note_list}")
endif()

file(GLOB_RECURSE markdown_files "${RUNNER_SOURCE_DIR}/*.md")
set(mission_documents "")
foreach(path IN LISTS markdown_files)
    if(path MATCHES "/build/")
        continue()
    endif()
    get_filename_component(name "${path}" NAME)
    string(TOLOWER "${name}" lower_name)
    if(lower_name MATCHES "mission" AND NOT lower_name STREQUAL "missioncache.md")
        list(APPEND mission_documents "${path}")
    endif()
endforeach()
if(mission_documents)
    list(JOIN mission_documents ", " mission_document_list)
    message(FATAL_ERROR "Duplicate mission documents remain: ${mission_document_list}")
endif()

foreach(stale IN ITEMS artifact published-audit published-final published-preliminary release-stage validation)
    if(EXISTS "${RUNNER_SOURCE_DIR}/${stale}")
        message(FATAL_ERROR "Stale release directory remains: ${stale}")
    endif()
endforeach()
if(EXISTS "${RUNNER_SOURCE_DIR}/src/autonomy.cpp")
    message(FATAL_ERROR "Obsolete monolithic autonomy.cpp remains")
endif()

file(READ "${RUNNER_SOURCE_DIR}/CMakeLists.txt" cmake_text)
string(FIND "${cmake_text}" "project(Runner VERSION 0.7.15 LANGUAGES CXX)" version_position)
if(version_position EQUAL -1)
    message(FATAL_ERROR "CMake project version is not 0.7.15")
endif()

file(READ "${RUNNER_SOURCE_DIR}/README.md" readme_text)
foreach(reference IN ITEMS "CHANGELOG.md" "missioncache.md" "SANDHYBRID_INTEGRATION_BRIDGE.md" "--diagnose-acceptance")
    string(FIND "${readme_text}" "${reference}" reference_position)
    if(reference_position EQUAL -1)
        message(FATAL_ERROR "README is missing required reference: ${reference}")
    endif()
endforeach()

file(READ "${RUNNER_SOURCE_DIR}/src/acceptance.cpp" acceptance_text)
foreach(reference IN ITEMS "std::hypot" "!cases.empty()" "8. MIXED GOAL COURSE")
    string(FIND "${acceptance_text}" "${reference}" reference_position)
    if(reference_position EQUAL -1)
        message(FATAL_ERROR "Acceptance hardening is missing: ${reference}")
    endif()
endforeach()
message(STATUS "Runner repository hygiene passed")